
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: saurav
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default 
  source:
    repoURL: "https://github.com/Ashvanipandey/gitops.git"
    targetRevision: main
    path: . 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
